Repository numba/numba-scipy, pull requests merged in 2022-06, with the labels that each got.

#81 Update Azure CI to windows-2019 following Numba's config
  azure-pipelines.yml
Labels: 3 - Ready for Review

#78 Continue PR #76: Upgrade scipy to 1.7.3
  .github/workflows/test_and_deploy.yml
  buildscripts/conda_recipes/numba-scipy/meta.yaml
  setup.py
Labels: 4 - Waiting on reviewer

#70 docs upgrade
  README.rst
  docs/source/developer/contributing.rst
Labels: doc, 5 - Ready to merge

#84 Update changelog 0.3.1
  CHANGE_LOG
Labels: 3 - Ready for Review
